function mlxkit_setup_compat(gendir)
  % Generate compatibility shims in gendir and put them first on the path.
  %
  % ODE solvers: MATLAB still accepts extra arguments after the options and
  % passes them on to the ODE function; Octave ignores them. Octave's own
  % solvers are copied under private names (with their private helpers) and
  % wrapped by shims that fold the extra arguments into the function handle.
  warning('off', 'Octave:shadowed-function');
  if ~exist(gendir, 'dir'), mkdir(gendir); end
  solvers = {'ode45', 'ode23', 'ode15s', 'ode23s'};
  for i = 1:numel(solvers)
    name = solvers{i};
    orig = which(name);
    if isempty(orig), continue; end
    src = fileread(orig);
    src = regexprep(src, ['(function\s+varargout\s*=\s*)' name '(?=\W)'], ['$1mlxkit_orig_' name], 'once');
    write_file(fullfile(gendir, ['mlxkit_orig_' name '.m']), src);
    privdir = fullfile(fileparts(orig), 'private');
    if exist(privdir, 'dir') && ~exist(fullfile(gendir, 'private'), 'dir')
      copyfile(privdir, fullfile(gendir, 'private'));
    end
    write_file(fullfile(gendir, [name '.m']), strrep(shim_template(), 'NAME', name));
  end
  % set(): MATLAB accepts defaults for object types Octave doesn't know about
  % (e.g. defaultLegendInterpreter); drop just those instead of failing.
  write_file(fullfile(gendir, 'set.m'), sprintf([ ...
    'function varargout = set(varargin)\n' ...
    '  %% mlxkit shim: ignore default properties Octave does not support.\n' ...
    '  try\n' ...
    '    [varargout{1:nargout}] = builtin(''set'', varargin{:});\n' ...
    '  catch err\n' ...
    '    if ~strcmp(err.message, ''invalid default property specification''), rethrow(err); end\n' ...
    '    args = varargin;\n' ...
    '    keep = true(size(args));\n' ...
    '    for i = 2:2:numel(args) - 1\n' ...
    '      if ischar(args{i}) && strncmpi(args{i}, ''default'', 7)\n' ...
    '        try\n' ...
    '          builtin(''set'', args{1}, args{i}, args{i+1});\n' ...
    '        catch\n' ...
    '        end\n' ...
    '        keep(i:i+1) = false;\n' ...
    '      end\n' ...
    '    end\n' ...
    '    if any(keep(2:end)), builtin(''set'', args{keep}); end\n' ...
    '  end\n' ...
    'end\n']));
  % Load every installed Octave package (statistics, symbolic, datatypes, ...)
  % since MATLAB toolboxes are available without an explicit load.
  try
    pkgs = pkg('list');
    for i = 1:numel(pkgs)
      try
        pkg('load', pkgs{i}.name);
      catch
      end
    end
  catch
  end
  addpath(gendir);
  addpath(fullfile(fileparts(mfilename('fullpath')), 'compat'));
end

function t = shim_template()
  t = [ ...
    'function varargout = NAME(fcn, tspan, y0, varargin)\n' ...
    '  %% mlxkit shim: pass MATLAB-style extra arguments on to fcn.\n' ...
    '  if numel(varargin) > 1\n' ...
    '    extra = varargin(2:end);\n' ...
    '    f = fcn;\n' ...
    '    if ischar(f), f = str2func(f); end\n' ...
    '    fcn = @(t, y) f(t, y, extra{:});\n' ...
    '    varargin = varargin(1);\n' ...
    '  end\n' ...
    '  if numel(varargin) == 1 && isempty(varargin{1}), varargin = {}; end\n' ...
    '  if nargout == 0\n' ...
    '    mlxkit_orig_NAME(fcn, tspan, y0, varargin{:});\n' ...
    '  else\n' ...
    '    [varargout{1:nargout}] = mlxkit_orig_NAME(fcn, tspan, y0, varargin{:});\n' ...
    '  end\n' ...
    'end\n'];
  t = sprintf(t);
end

function write_file(name, txt)
  fid = fopen(name, 'w');
  fwrite(fid, txt);
  fclose(fid);
end
